baseURL = 'https://notanexpert.fyi/'
languageCode = 'en-us'
title = 'Not An Expert'
theme = 'simple-portfolio'

[params]
  description = 'Learning in public. Experiments, prototypes, and thinking out loud.'
  author = 'Tim'
  
[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Projects'
    url = '/projects/'
    weight = 2
  [[menu.main]]
    name = 'Tools'
    url = '/tools/'
    weight = 3
  [[menu.main]]
    name = 'Notes'
    url = '/notes/'
    weight = 4
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 5

[outputs]
  home = ['HTML', 'RSS']
